#!/usr/bin/env bash
# Migration script

# generate: revision --autogenerate
# upgrade: upgrade head
# downgrade: downgrade head

run_alembic() {
    PYTHONPATH=. alembic $*
}

case "$1" in
    generate)
        run_alembic revision --autogenerate
        ;;
    upgrade)
        run_alembic upgrade head
        ;;
    downgrade)
        run_alembic downgrade head
        ;;
    *)
        run_alembic $*
esac
