#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from argparse import ArgumentParser

from thermostat import app, database

parser = ArgumentParser(__doc__)
parser.add_argument('-p', '--port', type=int, default=7475, help='port to listen for API calls')
parser.add_argument('--host', default='127.0.0.1', help='host to bind for API calls')
parser.add_argument('-c', '--config', type=str, default='/etc/thermostat.conf', help='path to configuration file')
parser.add_argument('-d', '--debug', action='store_true', help='enable debug')
args = parser.parse_args()

app.config.from_pyfile(args.config)
app.database = database.init(app.config)
app.run(host=args.host, port=args.port, workers=1, debug=args.debug)
